# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
import sys
sys.path.append('/path/to/directory/containing/initialise.py')

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [ ]:
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep139863411681952
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
   

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [ ]:
a= np.zeros((5,5))
print("%d bytes" % (a.size * a.itemsize))

200 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a=np.zeros(10)
a[4]=1
print("array",a)

array [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
a=np.arange(10,50)
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
a=np.nonzero([1,2,0,0,4,0])
a

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a=np.random.random((3,3,3))
a

array([[[0.19452144, 0.86310751, 0.97351951],
        [0.73511912, 0.79066052, 0.11137918],
        [0.01070312, 0.64665934, 0.95449639]],

       [[0.49301426, 0.73733682, 0.67367137],
        [0.99683989, 0.56670087, 0.2802631 ],
        [0.9302727 , 0.8077308 , 0.1531333 ]],

       [[0.62892581, 0.49598016, 0.30153756],
        [0.21823214, 0.41412886, 0.29596621],
        [0.66884965, 0.99050372, 0.46580141]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a=np.random.random((10,10))
print(a.min())
print(a.max())

0.02479256505129135
0.9956902964591285


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a=np.random.random(30)
a.mean()

0.5369670312690704

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a=np.ones((10,10))
a[1:-1,1:-1]=0
a


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
a=np.ones((5,10))
a=np.pad(a,pad_width=1,mode='constant',constant_values=0)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
a=0*np.nan
b=np.nan==np.nan
c=np.inf>np.nan
d=np.nan-np.nan
e=np.nan in set([np.nan])
f=0.3==3*0.1

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
a=np.diag(1+np.arange(4),k=-1)
a

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a=np.zeros((8,8))
a[1::2,::2]=1
a[::2,1::2]=1
a

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [ ]:
a=np.unravel_index(100,(6,7,8))
a

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a=np.tile(np.array([[0,1],[1,0]]),(4,4))
a

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a=np.random.random((5,5))
a=(a-np.mean(a))/np.std(a)
a

array([[ 1.03225884, -0.3060896 ,  0.45285551,  1.09752455, -1.53347482],
       [-0.16636004, -0.15316807,  1.02458465,  0.96142772, -0.02342069],
       [ 1.36553414,  0.56148953, -2.05412964,  1.40142038, -1.58392352],
       [ 1.11702293, -0.9214145 ,  0.26605637,  0.11957481, -0.62612787],
       [-0.10144355, -0.54193266, -1.30472931, -1.18148598,  1.09795081]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])
a

<ipython-input-29-643e6e996a4a>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.dtype([("r",np.ubyte,1),("g",np.ubyte,1),("b",np.ubyte,1),("a",np.ubyte,1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
a=np.dot(np.ones((5,3)),np.ones((3,2)))
a

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a=np.arange(11)
a[(3<a)&(a<=8)]*=-1
a

array([ 0,  1,  2,  3, -4, -5, -6, -7, -8,  9, 10])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
a=sum(range(5),-1)
print(a)
b=np.sum(range(5),-1)
print(b)

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
a=np.arange(5)
print(a**a)
print(2<<a>>2)
print(a<-a)
print(1j*a)
print(a/1/1)
print(np.any((a < a) & (a > a)))
print(np.all((a < a) & (a > a)))

[  1   1   4  27 256]
[0 1 2 4 8]
[False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j]
[0. 1. 2. 3. 4.]
False
False


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [3]:
a=np.array(0) / np.array(0)
b=np.array(0) // np.array(0)
c=np.array([np.nan]).astype(int).astype(float)
print(a,b,c)


nan 0 [-9.22337204e+18]


<ipython-input-3-894266350285>:1: RuntimeWarning: invalid value encountered in divide
  a=np.array(0) / np.array(0)
<ipython-input-3-894266350285>:2: RuntimeWarning: divide by zero encountered in floor_divide
  b=np.array(0) // np.array(0)
<ipython-input-3-894266350285>:3: RuntimeWarning: invalid value encountered in cast
  c=np.array([np.nan]).astype(int).astype(float)


#### 29. How to round away from zero a float array ? (★☆☆)

In [ ]:
a=np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(a)),a))

[-7.  7.  9.  9.  1.  6.  5. -1. -6.  8.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
a=np.random.randint(0,10,10)
b=np.random.randint(0,10,10)
print(np.intersect1d(a,b))

[0 2 4 5 7 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
a=np.seterr(all="ignore")
a

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
a=np.sqrt(-1) == np.emath.sqrt(-1)
a

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [ ]:
a=np.datetime64('today','D')-np.timedelta64(1,'D')
b=np.datetime64('today','D')
c=np.datetime64('today','D')+np.timedelta64(1,'D')
print(a,b,c)

2024-12-01 2024-12-02 2024-12-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [ ]:
a=np.arange('2016-07','2016-08',dtype='datetime64[D]')
a


array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [4]:
a=np.ones(3)*1
b=np.ones(3)*2
np.add(a,b,out=b)
np.divide(a,2,out=a)
np.negative(a,out=a)
np.multiply(a,b,out=a)


array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [5]:
a=np.random.uniform(0,10,10)
print(a-a%1)
print(np.floor(a))
print(np.ceil(a)-1)
print(a.astype(int))
print(np.trunc(a))

[8. 5. 0. 2. 7. 0. 9. 6. 7. 6.]
[8. 5. 0. 2. 7. 0. 9. 6. 7. 6.]
[8. 5. 0. 2. 7. 0. 9. 6. 7. 6.]
[8 5 0 2 7 0 9 6 7 6]
[8. 5. 0. 2. 7. 0. 9. 6. 7. 6.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [6]:
a=np.zeros((5,5))
a+=np.arange(5)
a

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [7]:
a=np.random.randint(10,size=10)
a

array([8, 9, 8, 2, 6, 7, 5, 7, 8, 0])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [8]:
a=np.linspace(0,1,11,endpoint=False)[1:]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [9]:
a=np.random.random(10)
a.sort()
a

array([0.04367365, 0.07928887, 0.13120089, 0.54395445, 0.62649305,
       0.74743649, 0.77361145, 0.79944147, 0.84059303, 0.93559723])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [10]:
a=np.arange(10)
np.add.reduce(a)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [11]:
a=np.random.randint(0,2,5)
b=np.random.randint(0,2,5)
print(np.allclose(a,b))
print(np.array_equal(a,b))

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [13]:
a=np.zeros(10)
a.flags.writeable=False
a[0]=1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [14]:
a=np.random.random((10,2))
x,y=a[:,0],a[:,1]
r=np.sqrt(x**2+y**2)
t=np.arctan2(y,x)
print(r)
print(t)

[1.39894393 1.09201725 0.97003438 0.12973763 0.15574211 1.02626718
 1.01222413 0.61407598 1.07376149 0.58289782]
[0.78865401 0.78188689 1.43348482 0.06041985 0.41529806 1.26866941
 1.39242078 0.12505838 0.88344403 1.04820982]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [15]:
a=np.random.random(10)
a[a.argmax()]=0
a

array([0.2395634 , 0.20243716, 0.41422881, 0.35388664, 0.36284965,
       0.88644774, 0.        , 0.67588114, 0.20885585, 0.25963004])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [16]:
a=np.zeros((5,5),[('x',float),('y',float)])
a['x'],a['y']=np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
a

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [17]:
a=np.arange(8)
b=a+0.5
c=1.0/np.subtract.outer(a,b)
print(np.linalg.det(c))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [18]:
a=np.array([np.int8,np.int32,np.int64])
for i in a:
    print(np.iinfo(i).min)
    print(np.iinfo(i).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807


#### 49. How to print all the values of an array? (★★☆)

In [19]:
a=np.zeros((16,16))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [20]:
a=np.arange(100)
b=np.random.uniform(0,100)
index=(np.abs(a-b)).argmin()
print(a[index])

81


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [21]:
a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])
a

<ipython-input-21-aa173d70e449>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a=np.zeros(10,[('position',[('x',float,1),('y',float,1)]),('color',[('r',float,1),('g',float,1),('b',float,1)])])


array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [22]:
a=np.random.random((10,2))
x,y=np.atleast_2d(a[:,0],a[:,1])
d=np.sqrt((x-x.T)**2+(y-y.T)**2)
d

array([[0.        , 0.34469216, 0.55070325, 0.56446127, 0.87641658,
        0.36035682, 0.94799065, 0.79918601, 0.84007115, 0.69757092],
       [0.34469216, 0.        , 0.51981201, 0.51289716, 0.59441264,
        0.01644505, 0.75044299, 0.70624474, 0.61913513, 0.7998834 ],
       [0.55070325, 0.51981201, 0.        , 0.03261399, 0.56155344,
        0.52870497, 0.47298129, 0.25371175, 0.42153222, 0.33093987],
       [0.56446127, 0.51289716, 0.03261399, 0.        , 0.52940768,
        0.52092954, 0.44293334, 0.23528772, 0.38908279, 0.3581128 ],
       [0.87641658, 0.59441264, 0.56155344, 0.52940768, 0.        ,
        0.58684405, 0.29375519, 0.49566328, 0.18885497, 0.87170038],
       [0.36035682, 0.01644505, 0.52870497, 0.52092954, 0.58684405,
        0.        , 0.74872216, 0.71085706, 0.61639177, 0.8121204 ],
       [0.94799065, 0.75044299, 0.47298129, 0.44293334, 0.29375519,
        0.74872216, 0.        , 0.28476453, 0.13857379, 0.70908203],
       [0.79918601, 0.70624474, 0.2537117

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [23]:
a=np.arange(10,dtype=np.float32)
a=a.astype(np.int32,copy=False)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [24]:
a=np.genfromtxt("missing.txt",delimiter=",",dtype=np.int)
a

AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [25]:
a=np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(a):
    print(index,value)
for index in np.ndindex(a.shape):
    print(index,a[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [26]:
a=np.random.random((5,5))
x,y=np.meshgrid(np.linspace(-1,1,5),np.linspace(-1,1,5))
a=np.sqrt(x*x+y*y)
sigma,mu=1.0,0.0
b=np.exp(-((a-mu)**2/(2.0*sigma**2)))
b

array([[0.36787944, 0.53526143, 0.60653066, 0.53526143, 0.36787944],
       [0.53526143, 0.77880078, 0.8824969 , 0.77880078, 0.53526143],
       [0.60653066, 0.8824969 , 1.        , 0.8824969 , 0.60653066],
       [0.53526143, 0.77880078, 0.8824969 , 0.77880078, 0.53526143],
       [0.36787944, 0.53526143, 0.60653066, 0.53526143, 0.36787944]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [27]:
a=np.zeros((5,5))
np.put(a,np.random.choice(range(5*5),5,replace=False),1)
a

array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [28]:
a=np.random.rand(5,10)
b=a-a.mean(axis=1,keepdims=True)
b

array([[ 0.34899009, -0.40113851, -0.07078916, -0.1671863 ,  0.13687611,
        -0.23870637,  0.25063415,  0.18623287, -0.0625626 ,  0.01764971],
       [-0.0047399 , -0.21868912, -0.21793212,  0.4756572 , -0.31471629,
        -0.05710737, -0.22251942,  0.58924195,  0.16900753, -0.19820247],
       [ 0.24033638, -0.42212526,  0.24727105,  0.35518851, -0.05000901,
        -0.45978813, -0.50220907,  0.06215848,  0.24868567,  0.28049138],
       [ 0.07286706, -0.38807146, -0.04784719,  0.44870369, -0.18764909,
         0.11082094, -0.16392445,  0.38151373, -0.4187605 ,  0.19234725],
       [-0.41812503, -0.39258787, -0.40841102, -0.23977158, -0.00312073,
         0.34504067,  0.43185034,  0.37445385,  0.13254059,  0.17813077]])

#### 59. How to sort an array by the nth column? (★★☆)

In [29]:
a=np.random.randint(0,10,(3,3))
print(a)
print(a[a[:,1].argsort()])

[[6 3 9]
 [2 0 6]
 [5 8 8]]
[[2 0 6]
 [6 3 9]
 [5 8 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [30]:
a=np.random.randint(0,3,(3,10))
print((~a.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [31]:
a=np.random.uniform(0,1,10)
b=0.5
c=a.flat[np.abs(a-b).argmin()]
c

0.46003447874995407

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [33]:
a=np.arange(3).reshape(3,1)
b=np.arange(3).reshape(1,3)
it=np.nditer([a,b,None])
for x,y,z in it:
    z[...]=x+y
    print(it.operands[2])


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 1 0]
 [0 0 0]
 [0 0 0]]
[[0 1 2]
 [0 0 0]
 [0 0 0]]
[[0 1 2]
 [1 0 0]
 [0 0 0]]
[[0 1 2]
 [1 2 0]
 [0 0 0]]
[[0 1 2]
 [1 2 3]
 [0 0 0]]
[[0 1 2]
 [1 2 3]
 [2 0 0]]
[[0 1 2]
 [1 2 3]
 [2 3 0]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [41]:
a=np.zeros(10)
a.flags.writeable=False
a[0]=1
print(a)

ValueError: assignment destination is read-only

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [35]:
a=np.ones(10)
b=np.random.randint(0,len(a),20)
a+=np.bincount(b,minlength=len(a))
a

array([4., 4., 2., 3., 4., 1., 2., 5., 3., 2.])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [36]:
a=[1,2,3,4,5,6]
b=[1,3,9,3,4,1]
c=np.bincount(b,a)
c

array([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.])

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [37]:
a=np.random.randint(0,2,(6,6,3)).astype(np.ubyte)
b=a[...,0]*256*256+a[...,1]*256+a[...,2]
c=len(np.unique(b))
c

4

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [38]:
a=np.random.randint(0,10,(3,4,3,4))
b=a.reshape(a.shape[:-2]+(-1,)).sum(axis=-1)
b

array([[61, 70, 51, 56],
       [61, 71, 51, 29],
       [40, 55, 51, 63]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [39]:
a=np.random.uniform(0,1,100)
b=np.random.randint(0,10,100)
c=np.bincount(b,weights=a)
d=np.bincount(b)
e=c/d
print(e)

[0.50245904 0.36268442 0.63565644 0.57478162 0.50081838 0.48373449
 0.39662701 0.62268025 0.5733692  0.53137916]


#### 69. How to get the diagonal of a dot product? (★★★)

In [42]:
a=np.random.uniform(0,1,(5,5))
b=np.random.uniform(0,1,(5,5))
np.diag(np.dot(a,b))
print(np.sum(a*b.T,axis=1))
print(np.einsum("ij,ji->i",a,b))

[1.23204539 1.47384932 0.48313961 1.93417838 1.62390197]
[1.23204539 1.47384932 0.48313961 1.93417838 1.62390197]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [43]:
a=np.array([1,2,3,4,5])
b=3
c=np.zeros(len(a)+(len(a)-1)*(b))
c[::b+1]=a
c

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [44]:
a=np.ones((5,5,3))
b=2*np.ones((5,5))
print(a*b[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [45]:
a=np.arange(25).reshape(5,5)
a[[0,1]]=a[[1,0]]
a

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [46]:
a=np.random.randint(0,100,(10,3))
b=np.roll(a.repeat(2,axis=1),-1,axis=1)
b=b.reshape(len(b)*3,2)
b=np.sort(b,axis=1)
c=b.view(dtype=[('p0',b.dtype),('p1',b.dtype)])
d=np.unique(c)
d

array([( 3, 45), ( 3, 83), ( 7, 12), ( 7, 95), (12, 95), (15, 28),
       (15, 79), (26, 41), (26, 63), (28, 48), (28, 62), (28, 79),
       (40, 94), (41, 63), (45, 83), (48, 62), (51, 80), (51, 86),
       (58, 70), (58, 80), (58, 83), (58, 91), (70, 80), (80, 86),
       (83, 91), (88, 96), (88, 97), (94, 94), (96, 97)],
      dtype=[('p0', '<i8'), ('p1', '<i8')])

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [47]:
a=np.bincount([1,1,2,3,4,4,6])
b=np.repeat(np.arange(len(a)),a)
b

array([1, 1, 2, 3, 4, 4, 6])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [48]:
a=np.arange(20)
b=3
c=np.cumsum(a,dtype=float)
c[b:]=c[b:]-c[:-b]
c=c[b-1:]/b
c

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [51]:
a=np.arange(10)
b=3
c=a.reshape(len(a)-b+1,b)
print(c)

ValueError: cannot reshape array of size 10 into shape (8,3)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [52]:
a=np.random.randint(0,2,100)
np.logical_not(a,out=a)
a=np.random.uniform(-1.0,1.0,100)
np.negative(a,out=a)


array([ 9.72286682e-01,  3.43921483e-01,  3.03941142e-01, -3.61283382e-01,
        6.54231550e-01, -2.31226186e-01, -4.56352618e-03,  6.98051044e-01,
       -8.03194980e-01, -4.11084408e-01,  9.91344343e-02,  6.70864723e-01,
       -4.11757357e-01,  3.25565573e-01, -2.62479997e-01, -4.59190173e-01,
       -9.73354682e-01,  8.15018665e-01,  6.96819194e-04,  1.95085222e-01,
        6.79050243e-02, -4.78787106e-01, -3.19411559e-01, -7.80986642e-01,
       -9.02102801e-01, -2.10022131e-02, -7.52350499e-01,  6.83742863e-01,
        1.90584316e-01,  2.78942322e-01, -6.87180883e-01,  7.67708976e-02,
        2.56516359e-01,  8.87085100e-01,  1.41878819e-01,  7.27800517e-01,
        6.15089547e-01, -3.75872463e-01, -8.76583224e-01, -3.28811145e-01,
        6.34502447e-01,  6.81680763e-03, -1.45455046e-01,  2.49262294e-01,
        7.40330704e-01, -5.11878732e-02,  1.25297329e-01,  9.99196229e-02,
        3.99125723e-01,  4.28561382e-01,  8.37530878e-01,  3.19747079e-01,
        1.62049454e-01,  

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [58]:
def distance_point_to_line(p0, p1, p):
    v = p1 - p0
    w = p - p0

    c1 = np.dot(w, v)
    c2 = np.dot(v, v)

    if c2 == 0:
      return np.linalg.norm(p - p0)

    b = c1 / c2

    closest_point = p0 + b * v
    distance = np.linalg.norm(p - closest_point)

    return
    distance


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [59]:
a=np.random.uniform(-10,10,(10,2))
b=np.random.uniform(-10,10,(10,2))
c=np.random.uniform(-10,10,(10,2))
print(np.array([distance_point_to_line(a,b,c_i) for c_i in c]))


ValueError: shapes (10,2) and (10,2) not aligned: 2 (dim 1) != 10 (dim 0)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [61]:
a=np.asarray([[1.0, 0.0, 0.0, 0.0],
])

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [60]:
a=np.random.randn(100)
n=1000
idx=np.random.randint(0,a.size,(n,a.size))
means=a[idx].mean(axis=1)
